"""add price to products

Revision ID: ca27626a07a8
Revises: 8cb10fbb8085
Create Date: 2025-10-14 16:05:42.794120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca27626a07a8'
down_revision: Union[str, Sequence[str], None] = '8cb10fbb8085'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1️⃣ Añadir la columna como nullable
    op.add_column('products', sa.Column('price', sa.Integer(), nullable=True))

    # 2️⃣ Asignar un valor por defecto (backfill para registros existentes)
    op.execute("UPDATE products SET price = 0 WHERE price IS NULL")

    # 3️⃣ Hacer la columna NOT NULL
    op.alter_column('products', 'price', existing_type=sa.Integer(), nullable=False)



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'price')
    # ### end Alembic commands ###
